
import { type BibleBook } from './types';

export const bibleBooks: BibleBook[] = [
  { name: 'Gênesis', abbrev: { pt: 'genesis', en: 'gn' }, chapters: 50, testament: 'VT' },
  { name: 'Êxodo', abbrev: { pt: 'exodus', en: 'ex' }, chapters: 40, testament: 'VT' },
  { name: 'Levítico', abbrev: { pt: 'leviticus', en: 'lv' }, chapters: 27, testament: 'VT' },
  { name: 'Números', abbrev: { pt: 'numbers', en: 'nm' }, chapters: 36, testament: 'VT' },
  { name: 'Deuteronômio', abbrev: { pt: 'deuteronomy', en: 'dt' }, chapters: 34, testament: 'VT' },
  { name: 'Josué', abbrev: { pt: 'joshua', en: 'js' }, chapters: 24, testament: 'VT' },
  { name: 'Juízes', abbrev: { pt: 'judges', en: 'jz' }, chapters: 21, testament: 'VT' },
  { name: 'Rute', abbrev: { pt: 'ruth', en: 'rt' }, chapters: 4, testament: 'VT' },
  { name: '1º Samuel', abbrev: { pt: '1samuel', en: '1sm' }, chapters: 31, testament: 'VT' },
  { name: '2º Samuel', abbrev: { pt: '2samuel', en: '2sm' }, chapters: 24, testament: 'VT' },
  { name: '1º Reis', abbrev: { pt: '1kings', en: '1rs' }, chapters: 22, testament: 'VT' },
  { name: '2º Reis', abbrev: { pt: '2kings', en: '2rs' }, chapters: 25, testament: 'VT' },
  { name: '1º Crônicas', abbrev: { pt: '1chronicles', en: '1cr' }, chapters: 29, testament: 'VT' },
  { name: '2º Crônicas', abbrev: { pt: '2chronicles', en: '2cr' }, chapters: 36, testament: 'VT' },
  { name: 'Esdras', abbrev: { pt: 'ezra', en: 'ed' }, chapters: 10, testament: 'VT' },
  { name: 'Neemias', abbrev: { pt: 'nehemiah', en: 'ne' }, chapters: 13, testament: 'VT' },
  { name: 'Ester', abbrev: { pt: 'esther', en: 'et' }, chapters: 10, testament: 'VT' },
  { name: 'Jó', abbrev: { pt: 'job', en: 'job' }, chapters: 42, testament: 'VT' },
  { name: 'Salmos', abbrev: { pt: 'psalms', en: 'sl' }, chapters: 150, testament: 'VT' },
  { name: 'Provérbios', abbrev: { pt: 'proverbs', en: 'pv' }, chapters: 31, testament: 'VT' },
  { name: 'Eclesiastes', abbrev: { pt: 'ecclesiastes', en: 'ec' }, chapters: 12, testament: 'VT' },
  { name: 'Cânticos', abbrev: { pt: 'songofsolomon', en: 'ct' }, chapters: 8, testament: 'VT' },
  { name: 'Isaías', abbrev: { pt: 'isaiah', en: 'is' }, chapters: 66, testament: 'VT' },
  { name: 'Jeremias', abbrev: { pt: 'jeremiah', en: 'jr' }, chapters: 52, testament: 'VT' },
  { name: 'Lamentações de Jeremias', abbrev: { pt: 'lamentations', en: 'lm' }, chapters: 5, testament: 'VT' },
  { name: 'Ezequiel', abbrev: { pt: 'ezekiel', en: 'ez' }, chapters: 48, testament: 'VT' },
  { name: 'Daniel', abbrev: { pt: 'daniel', en: 'dn' }, chapters: 12, testament: 'VT' },
  { name: 'Oséias', abbrev: { pt: 'hosea', en: 'os' }, chapters: 14, testament: 'VT' },
  { name: 'Joel', abbrev: { pt: 'joel', en: 'jl' }, chapters: 3, testament: 'VT' },
  { name: 'Amós', abbrev: { pt: 'amos', en: 'am' }, chapters: 9, testament: 'VT' },
  { name: 'Obadias', abbrev: { pt: 'obadiah', en: 'ob' }, chapters: 1, testament: 'VT' },
  { name: 'Jonas', abbrev: { pt: 'jonah', en: 'jn' }, chapters: 4, testament: 'VT' },
  { name: 'Miquéias', abbrev: { pt: 'micah', en: 'mq' }, chapters: 7, testament: 'VT' },
  { name: 'Naum', abbrev: { pt: 'nahum', en: 'na' }, chapters: 3, testament: 'VT' },
  { name: 'Habacuque', abbrev: { pt: 'habakkuk', en: 'hc' }, chapters: 3, testament: 'VT' },
  { name: 'Sofonias', abbrev: { pt: 'zephaniah', en: 'sf' }, chapters: 3, testament: 'VT' },
  { name: 'Ageu', abbrev: { pt: 'haggai', en: 'ag' }, chapters: 2, testament: 'VT' },
  { name: 'Zacarias', abbrev: { pt: 'zechariah', en: 'zc' }, chapters: 14, testament: 'VT' },
  { name: 'Malaquias', abbrev: { pt: 'malachi', en: 'ml' }, chapters: 4, testament: 'VT' },
  { name: 'Mateus', abbrev: { pt: 'matthew', en: 'mt' }, chapters: 28, testament: 'NT' },
  { name: 'Marcos', abbrev: { pt: 'mark', en: 'mc' }, chapters: 16, testament: 'NT' },
  { name: 'Lucas', abbrev: { pt: 'luke', en: 'lc' }, chapters: 24, testament: 'NT' },
  { name: 'João', abbrev: { pt: 'john', en: 'jo' }, chapters: 21, testament: 'NT' },
  { name: 'Atos', abbrev: { pt: 'acts', en: 'atos' }, chapters: 28, testament: 'NT' },
  { name: 'Romanos', abbrev: { pt: 'romans', en: 'rm' }, chapters: 16, testament: 'NT' },
  { name: '1ª Coríntios', abbrev: { pt: '1corinthians', en: '1co' }, chapters: 16, testament: 'NT' },
  { name: '2ª Coríntios', abbrev: { pt: '2corinthians', en: '2co' }, chapters: 13, testament: 'NT' },
  { name: 'Gálatas', abbrev: { pt: 'galatians', en: 'gl' }, chapters: 6, testament: 'NT' },
  { name: 'Efésios', abbrev: { pt: 'ephesians', en: 'ef' }, chapters: 6, testament: 'NT' },
  { name: 'Filipenses', abbrev: { pt: 'philippians', en: 'fp' }, chapters: 4, testament: 'NT' },
  { name: 'Colossenses', abbrev: { pt: 'colossians', en: 'cl' }, chapters: 4, testament: 'NT' },
  { name: '1ª Tessalonicenses', abbrev: { pt: '1thessalonians', en: '1ts' }, chapters: 5, testament: 'NT' },
  { name: '2ª Tessalonicenses', abbrev: { pt: '2thessalonians', en: '2ts' }, chapters: 3, testament: 'NT' },
  { name: '1ª Timóteo', abbrev: { pt: '1timothy', en: '1tm' }, chapters: 6, testament: 'NT' },
  { name: '2ª Timóteo', abbrev: { pt: '2timothy', en: '2tm' }, chapters: 4, testament: 'NT' },
  { name: 'Tito', abbrev: { pt: 'titus', en: 'tt' }, chapters: 3, testament: 'NT' },
  { name: 'Filemom', abbrev: { pt: 'philemon', en: 'fm' }, chapters: 1, testament: 'NT' },
  { name: 'Hebreus', abbrev: { pt: 'hebrews', en: 'hb' }, chapters: 13, testament: 'NT' },
  { name: 'Tiago', abbrev: { pt: 'james', en: 'tg' }, chapters: 5, testament: 'NT' },
  { name: '1ª Pedro', abbrev: { pt: '1peter', en: '1pe' }, chapters: 5, testament: 'NT' },
  { name: '2ª Pedro', abbrev: { pt: '2peter', en: '2pe' }, chapters: 3, testament: 'NT' },
  { name: '1ª João', abbrev: { pt: '1john', en: '1jo' }, chapters: 5, testament: 'NT' },
  { name: '2ª João', abbrev: { pt: '2john', en: '2jo' }, chapters: 1, testament: 'NT' },
  { name: '3ª João', abbrev: { pt: '3john', en: '3jo' }, chapters: 1, testament: 'NT' },
  { name: 'Judas', abbrev: { pt: 'jude', en: 'jd' }, chapters: 1, testament: 'NT' },
  { name: 'Apocalipse', abbrev: { pt: 'revelation', en: 'ap' }, chapters: 22, testament: 'NT' },
];
