
import { type BibleBook } from './types';

export const bibleBooks: BibleBook[] = [
  { name: 'Gênesis', abbrev: { pt: 'gn', en: 'gn' }, chapters: 50, testament: 'VT' },
  { name: 'Êxodo', abbrev: { pt: 'ex', en: 'ex' }, chapters: 40, testament: 'VT' },
  { name: 'Levítico', abbrev: { pt: 'lv', en: 'lv' }, chapters: 27, testament: 'VT' },
  { name: 'Números', abbrev: { pt: 'nm', en: 'nm' }, chapters: 36, testament: 'VT' },
  { name: 'Deuteronômio', abbrev: { pt: 'dt', en: 'dt' }, chapters: 34, testament: 'VT' },
  { name: 'Josué', abbrev: { pt: 'js', en: 'js' }, chapters: 24, testament: 'VT' },
  { name: 'Juízes', abbrev: { pt: 'jz', en: 'jz' }, chapters: 21, testament: 'VT' },
  { name: 'Rute', abbrev: { pt: 'rt', en: 'rt' }, chapters: 4, testament: 'VT' },
  { name: '1º Samuel', abbrev: { pt: '1sm', en: '1sm' }, chapters: 31, testament: 'VT' },
  { name: '2º Samuel', abbrev: { pt: '2sm', en: '2sm' }, chapters: 24, testament: 'VT' },
  { name: '1º Reis', abbrev: { pt: '1rs', en: '1rs' }, chapters: 22, testament: 'VT' },
  { name: '2º Reis', abbrev: { pt: '2rs', en: '2rs' }, chapters: 25, testament: 'VT' },
  { name: '1º Crônicas', abbrev: { pt: '1cr', en: '1cr' }, chapters: 29, testament: 'VT' },
  { name: '2º Crônicas', abbrev: { pt: '2cr', en: '2cr' }, chapters: 36, testament: 'VT' },
  { name: 'Esdras', abbrev: { pt: 'ed', en: 'ed' }, chapters: 10, testament: 'VT' },
  { name: 'Neemias', abbrev: { pt: 'ne', en: 'ne' }, chapters: 13, testament: 'VT' },
  { name: 'Ester', abbrev: { pt: 'et', en: 'et' }, chapters: 10, testament: 'VT' },
  { name: 'Jó', abbrev: { pt: 'job', en: 'job' }, chapters: 42, testament: 'VT' },
  { name: 'Salmos', abbrev: { pt: 'sl', en: 'sl' }, chapters: 150, testament: 'VT' },
  { name: 'Provérbios', abbrev: { pt: 'pv', en: 'pv' }, chapters: 31, testament: 'VT' },
  { name: 'Eclesiastes', abbrev: { pt: 'ec', en: 'ec' }, chapters: 12, testament: 'VT' },
  { name: 'Cânticos', abbrev: { pt: 'ct', en: 'ct' }, chapters: 8, testament: 'VT' },
  { name: 'Isaías', abbrev: { pt: 'is', en: 'is' }, chapters: 66, testament: 'VT' },
  { name: 'Jeremias', abbrev: { pt: 'jr', en: 'jr' }, chapters: 52, testament: 'VT' },
  { name: 'Lamentações de Jeremias', abbrev: { pt: 'lm', en: 'lm' }, chapters: 5, testament: 'VT' },
  { name: 'Ezequiel', abbrev: { pt: 'ez', en: 'ez' }, chapters: 48, testament: 'VT' },
  { name: 'Daniel', abbrev: { pt: 'dn', en: 'dn' }, chapters: 12, testament: 'VT' },
  { name: 'Oséias', abbrev: { pt: 'os', en: 'os' }, chapters: 14, testament: 'VT' },
  { name: 'Joel', abbrev: { pt: 'jl', en: 'jl' }, chapters: 3, testament: 'VT' },
  { name: 'Amós', abbrev: { pt: 'am', en: 'am' }, chapters: 9, testament: 'VT' },
  { name: 'Obadias', abbrev: { pt: 'ob', en: 'ob' }, chapters: 1, testament: 'VT' },
  { name: 'Jonas', abbrev: { pt: 'jn', en: 'jn' }, chapters: 4, testament: 'VT' },
  { name: 'Miquéias', abbrev: { pt: 'mq', en: 'mq' }, chapters: 7, testament: 'VT' },
  { name: 'Naum', abbrev: { pt: 'na', en: 'na' }, chapters: 3, testament: 'VT' },
  { name: 'Habacuque', abbrev: { pt: 'hc', en: 'hc' }, chapters: 3, testament: 'VT' },
  { name: 'Sofonias', abbrev: { pt: 'sf', en: 'sf' }, chapters: 3, testament: 'VT' },
  { name: 'Ageu', abbrev: { pt: 'ag', en: 'ag' }, chapters: 2, testament: 'VT' },
  { name: 'Zacarias', abbrev: { pt: 'zc', en: 'zc' }, chapters: 14, testament: 'VT' },
  { name: 'Malaquias', abbrev: { pt: 'ml', en: 'ml' }, chapters: 4, testament: 'VT' },
  { name: 'Mateus', abbrev: { pt: 'mt', en: 'mt' }, chapters: 28, testament: 'NT' },
  { name: 'Marcos', abbrev: { pt: 'mc', en: 'mc' }, chapters: 16, testament: 'NT' },
  { name: 'Lucas', abbrev: { pt: 'lc', en: 'lc' }, chapters: 24, testament: 'NT' },
  { name: 'João', abbrev: { pt: 'jo', en: 'jo' }, chapters: 21, testament: 'NT' },
  { name: 'Atos', abbrev: { pt: 'atos', en: 'atos' }, chapters: 28, testament: 'NT' },
  { name: 'Romanos', abbrev: { pt: 'rm', en: 'rm' }, chapters: 16, testament: 'NT' },
  { name: '1ª Coríntios', abbrev: { pt: '1co', en: '1co' }, chapters: 16, testament: 'NT' },
  { name: '2ª Coríntios', abbrev: { pt: '2co', en: '2co' }, chapters: 13, testament: 'NT' },
  { name: 'Gálatas', abbrev: { pt: 'gl', en: 'gl' }, chapters: 6, testament: 'NT' },
  { name: 'Efésios', abbrev: { pt: 'ef', en: 'ef' }, chapters: 6, testament: 'NT' },
  { name: 'Filipenses', abbrev: { pt: 'fp', en: 'fp' }, chapters: 4, testament: 'NT' },
  { name: 'Colossenses', abbrev: { pt: 'cl', en: 'cl' }, chapters: 4, testament: 'NT' },
  { name: '1ª Tessalonicenses', abbrev: { pt: '1ts', en: '1ts' }, chapters: 5, testament: 'NT' },
  { name: '2ª Tessalonicenses', abbrev: { pt: '2ts', en: '2ts' }, chapters: 3, testament: 'NT' },
  { name: '1ª Timóteo', abbrev: { pt: '1tm', en: '1tm' }, chapters: 6, testament: 'NT' },
  { name: '2ª Timóteo', abbrev: { pt: '2tm', en: '2tm' }, chapters: 4, testament: 'NT' },
  { name: 'Tito', abbrev: { pt: 'tt', en: 'tt' }, chapters: 3, testament: 'NT' },
  { name: 'Filemom', abbrev: { pt: 'fm', en: 'fm' }, chapters: 1, testament: 'NT' },
  { name: 'Hebreus', abbrev: { pt: 'hb', en: 'hb' }, chapters: 13, testament: 'NT' },
  { name: 'Tiago', abbrev: { pt: 'tg', en: 'tg' }, chapters: 5, testament: 'NT' },
  { name: '1ª Pedro', abbrev: { pt: '1pe', en: '1pe' }, chapters: 5, testament: 'NT' },
  { name: '2ª Pedro', abbrev: { pt: '2pe', en: '2pe' }, chapters: 3, testament: 'NT' },
  { name: '1ª João', abbrev: { pt: '1jo', en: '1jo' }, chapters: 5, testament: 'NT' },
  { name: '2ª João', abbrev: { pt: '2jo', en: '2jo' }, chapters: 1, testament: 'NT' },
  { name: '3ª João', abbrev: { pt: '3jo', en: '3jo' }, chapters: 1, testament: 'NT' },
  { name: 'Judas', abbrev: { pt: 'jd', en: 'jd' }, chapters: 1, testament: 'NT' },
  { name: 'Apocalipse', abbrev: { pt: 'ap', en: 'ap' }, chapters: 22, testament: 'NT' },
];
