export const text = {
  addExpense: 'Adicionar Despesa',
  myExpenses: 'Minhas Despesas',
  addExpenseSuccess: 'Despesa adicionada com sucesso.',
  addExpenseError: 'Falha ao adicionar despesa. Por favor, tente novamente.',
  deleteExpenseSuccess: 'Despesa deletada.',
  deleteExpenseError: 'Falha ao deletar despesa.',
  fetchExpensesError: 'Falha ao buscar despesas.',
  addNewExpense: 'Adicionar Nova Despesa',
  addNewExpenseDescription:
    'Preencha os detalhes abaixo para adicionar uma nova despesa à sua jornada.',
  description: 'Descrição',
  descriptionPlaceholder: 'Ex: Café',
  descriptionMinChars: 'A descrição deve ter pelo menos 2 caracteres.',
  amount: 'Valor',
  amountPlaceholder: '0.00',
  amountPositive: 'O valor deve ser um número positivo.',
  category: 'Categoria',
  selectCategory: 'Selecione uma categoria',
  pleaseSelectCategory: 'Por favor, selecione uma categoria.',
  expenseDate: 'Data da Despesa',
  pickDate: 'Escolha uma data',
  expenses: 'Despesas',
  date: 'Data',
  amountHeader: 'Valor',
  actions: 'Ações',
  deleteConfirmationTitle: 'Você tem certeza absoluta?',
  deleteConfirmationDescription:
    'Esta ação não pode ser desfeita. Isso excluirá permanentemente esta despesa de nossos servidores.',
  cancel: 'Cancelar',
  delete: 'Deletar',
  noExpensesYet: 'Você ainda não adicionou nenhuma despesa.',
  clickToAddExpense: "Clique em 'Adicionar Despesa' para começar sua jornada!",
  appName: 'A Jornada',
  logout: 'Sair',
  login: 'Entrar',
  googleSignIn: 'Entrar com Google',
  orContinueWith: 'Ou continue com',
  email: 'Email',
  emailPlaceholder: 'm@exemplo.com',
  password: 'Senha',
  welcomeBack: 'Bem-vindo de Volta',
  welcomeBackDescription: 'Faça login na sua conta para continuar sua jornada.',
  register: 'Registrar',
  startYourJourney: 'Comece Sua Jornada',
  startYourJourneyDescription: 'Crie uma conta para começar sua jornada.',
  signUpFailed: 'Falha no Cadastro',
  loginFailed: 'Falha no Login',
  googleSignInFailed: 'Falha no Login com Google',
  errorInvalidEmailPassword: 'Email ou senha inválidos.',
  errorEmailInUse: 'Este email já está em uso.',
  errorWeakPassword: 'A senha deve ter pelo menos 6 caracteres.',
  errorInvalidEmail: 'Por favor, insira um endereço de email válido.',
  errorPopupClosed: 'O processo de login foi cancelado.',
  errorUnexpected: 'Ocorreu um erro inesperado. Por favor, tente novamente.',
  appDescription: 'Sua jornada pessoal de controle de despesas',
  error: 'Erro',
  success: 'Sucesso',
  youMustBeLoggedIn: 'Você deve estar logado para adicionar uma despesa.',
};
