export const text = {
  header: {
    appName: 'A Jornada',
    appDescription: 'Sua jornada pessoal de controle de despesas',
    logout: 'Sair',
    profiles: 'Perfis',
    personal: 'Pessoal',
    home: 'Casa',
    business: 'Negócios',
  },
  auth: {
    login: 'Entrar',
    loginFailed: 'Falha no Login',
    register: 'Registrar',
    googleSignIn: 'Entrar com Google',
    googleSignInFailed: 'Falha no Login com Google',
    orContinueWith: 'Ou continue com',
    emailPlaceholder: 'm@exemplo.com',
    welcomeBack: 'Bem-vindo de Volta',
    welcomeBackDescription:
      'Faça login na sua conta para continuar sua jornada.',
    startYourJourney: 'Comece Sua Jornada',
    startYourJourneyDescription: 'Crie uma conta para começar sua jornada.',
    signUpFailed: 'Falha no Cadastro',
    errors: {
      invalidEmailPassword: 'Email ou senha inválidos.',
      emailInUse: 'Este email já está em uso.',
      weakPassword: 'A senha deve ter pelo menos 6 caracteres.',
      invalidEmail: 'Por favor, insira um endereço de email válido.',
      popupClosed: 'O processo de login foi cancelado.',
      unexpected: 'Ocorreu um erro inesperado. Por favor, tente novamente.',
    },
  },
  dashboard: {
    title: 'Lançamento',
    addExpense: 'Adicionar Despesa',
  },
  addExpenseForm: {
    title: 'Adicionar Nova Despesa',
    description:
      'Preencha os detalhes abaixo para adicionar uma nova despesa à sua jornada.',
    descriptionPlaceholder: 'Ex: Café',
    amountPlaceholder: '0,00',
    selectCategory: 'Selecione uma categoria',
    expenseDate: 'Data da Despesa',
    pickDate: 'Escolha uma data',
    addSuccess: 'Despesa adicionada com sucesso.',
    addError: 'Falha ao adicionar despesa. Por favor, tente novamente.',
    notLoggedIn: 'Você deve estar logado para adicionar uma despesa.',
    validation: {
      descriptionMinChars: 'A descrição deve ter pelo menos 2 caracteres.',
      amountPositive: 'O valor deve ser um número positivo.',
      pleaseSelectCategory: 'Por favor, selecione uma categoria.',
    },
  },
  expensesList: {
    title: 'Despesas',
    noExpenses: 'Você ainda não adicionou nenhuma despesa neste perfil.',
    clickToAdd: "Clique em 'Adicionar Despesa' para começar.",
    deleteSuccess: 'Despesa deletada.',
    deleteError: 'Falha ao deletar despesa.',
    fetchError: 'Falha ao buscar despesas.',
    deleteConfirmTitle: 'Você tem certeza absoluta?',
    deleteConfirmDescription:
      'Esta ação não pode ser desfeita. Isso excluirá permanentemente esta despesa de nossos servidores.',
  },
  common: {
    description: 'Descrição',
    amount: 'Valor',
    category: 'Categoria',
    date: 'Data',
    actions: 'Ações',
    password: 'Senha',
    email: 'Email',
    cancel: 'Cancelar',
    delete: 'Deletar',
    error: 'Erro',
    success: 'Sucesso',
  },
};
