export const text = {
  header: {
    appName: 'A Jornada',
    appDescription: 'Sua jornada de controle Financeiro',
    profiles: 'Perfis',
    personal: 'Joao',
    home: 'Casa',
    business: 'Farmacia',
    profileTypes: {
      personal: 'Personal',
      home: 'Home',
      business: 'Business',
    },
  },
  sidebar: {
    dashboard: 'Dashboard',
    releases: 'Lançamentos',
    reports: 'Relatórios',
    cards: 'Cartões',
    investments: 'Investimentos',
    payBill: 'Pagar Fatura',
  },
  dashboard: {
    title: 'Dashboard',
    annualSummaryTitle: 'Resumo Financeiro Anual',
    monthLabel: 'Mês',
    yearLabel: 'Ano',
    selectPlaceholder: 'Selecione',
    months: {
      january: 'Janeiro',
      february: 'Fevereiro',
      march: 'Março',
      april: 'Abril',
      may: 'Maio',
      june: 'Junho',
      july: 'Julho',
      august: 'Agosto',
      september: 'Setembro',
      october: 'Outubro',
      november: 'Novembro',
      december: 'Dezembro',
    },
  },
  auth: {
    login: 'Entrar',
    loginFailed: 'Falha no Login',
    register: 'Registrar',
    googleSignIn: 'Entrar com Google',
    googleSignInFailed: 'Falha no Login com Google',
    orContinueWith: 'Ou continue com',
    emailPlaceholder: 'm@exemplo.com',
    welcomeBack: 'Bem-vindo de Volta!',
    welcomeBackDescription:
      'Faça login na sua conta para continuar sua jornada.',
    startYourJourney: 'Comece Sua Jornada',
    startYourJourneyDescription: 'Crie uma conta para começar sua jornada.',
    signUpFailed: 'Falha no Cadastro',
    errors: {
      invalidEmailPassword: 'Email ou senha inválidos.',
      emailInUse: 'Este email já está em uso.',
      weakPassword: 'A senha deve ter pelo menos 6 caracteres.',
      invalidEmail: 'Por favor, insira um endereço de email válido.',
      popupClosed: 'O processo de login foi cancelado.',
      unexpected: 'Ocorreu um erro inesperado. Por favor, tente novamente.',
    },
  },
  summary: {
    totalBalance: 'Saldo Total',
    goToDashboard: 'Ver Lançamentos',
    newTransaction: 'Nova Despesa',
    newIncome: 'Nova Receita',
    income: 'Entradas',
    expenses: 'Saídas',
  },
  addCardForm: {
    title: 'Adicionar Novo Cartão',
    description: 'Cadastre um novo cartão para usar nos seus lançamentos.',
    cardName: 'Nome do Cartão',
    cardNamePlaceholder: 'Ex: Nubank, Inter, etc.',
    limit: 'Limite',
    limitPlaceholder: '5000,00',
    closingDay: 'Dia do Fechamento',
    dueDay: 'Dia do Vencimento',
    addCard: 'Adicionar Cartão',
    addNewCard: '+ Adicionar novo cartão',
  },
  addExpenseForm: {
    title: 'Adicionar Nova Despesa',
    description:
      'Preencha os detalhes abaixo para adicionar uma nova despesa à sua jornada.',
    descriptionPlaceholder: 'Ex: Café (Opcional)',
    amountPlaceholder: '0,00',
    selectCategory: 'Selecione uma categoria',
    selectSubcategory: 'Selecione uma subcategoria',
    noSubcategoryFound: 'Nenhuma subcategoria encontrada.',
    selectPaymentMethod: 'Selecione um meio de pagamento',
    expenseDate: 'Data da Despesa',
    pickDate: 'Escolha uma data',
    addExpense: 'Adicionar Despesa',
    addSuccess: 'Despesa adicionada com sucesso.',
    addError: 'Falha ao adicionar despesa. Por favor, tente novamente.',
    notLoggedIn: 'Você deve estar logado para adicionar uma despesa.',
    validation: {
      descriptionMinChars: 'A descrição deve ter pelo menos 2 caracteres.',
      amountPositive: 'O valor deve ser maior que zero.',
      amountRequired: 'O valor é obrigatório.',
      pleaseSelectCategory: 'Por favor, selecione uma categoria.',
      pleaseSelectSubcategory: 'Por favor, selecione uma subcategoria.',
      pleaseSelectPaymentMethod: 'Por favor, selecione um meio de pagamento.',
    },
  },
  addIncomeForm: {
    title: 'Adicionar Nova Receita',
    description: 'Preencha os detalhes para adicionar uma nova receita.',
    descriptionPlaceholder: 'Ex: Salário (Opcional)',
    amountPlaceholder: '0,00',
    selectCategory: 'Selecione uma categoria',
    selectSubcategory: 'Selecione uma subcategoria',
    incomeDate: 'Data da Receita',
    pickDate: 'Escolha uma data',
    addIncome: 'Adicionar Receita',
    addSuccess: 'Receita adicionada com sucesso.',
    addError: 'Falha ao adicionar receita. Por favor, tente novamente.',
    notLoggedIn: 'Você deve estar logado para adicionar uma receita.',
    validation: {
      amountPositive: 'O valor deve ser maior que zero.',
      amountRequired: 'O valor é obrigatório.',
      pleaseSelectCategory: 'Por favor, selecione uma categoria.',
      pleaseSelectSubcategory: 'Por favor, selecione uma subcategoria.',
    },
  },
  editExpenseForm: {
    title: 'Editar Despesa',
    description: 'Atualize os detalhes da sua despesa abaixo.',
    save: 'Salvar Alterações',
    updateSuccess: 'Despesa atualizada com sucesso.',
    updateError: 'Falha ao atualizar despesa. Por favor, tente novamente.',
  },
  editIncomeForm: {
    title: 'Editar Receita',
    description: 'Atualize os detalhes da sua receita abaixo.',
    save: 'Salvar Alterações',
    updateSuccess: 'Receita atualizada com sucesso.',
    updateError: 'Falha ao atualizar receita. Por favor, tente novamente.',
  },
  expensesList: {
    title: 'Histórico de Despesas',
    noExpenses: 'Você ainda não adicionou nenhuma despesa neste perfil.',
    clickToAdd: "Use o botão 'Nova Despesa' para começar.",
    deleteSuccess: 'Despesa deletada.',
    deleteError: 'Falha ao deletar despesa.',
    fetchError: 'Falha ao buscar despesas.',
    deleteConfirmTitle: 'Você tem certeza absoluta?',
    deleteConfirmDescription:
      'Esta ação não pode ser desfeita. Isso excluirá permanentemente esta despesa de nossos servidores.',
  },
  incomesList: {
    title: 'Histórico de Receitas',
    noIncomes: 'Você ainda não adicionou nenhuma receita neste perfil.',
    clickToAdd: "Use o botão 'Nova Receita' para começar.",
    deleteSuccess: 'Receita deletada.',
    deleteError: 'Falha ao deletar receita.',
    fetchError: 'Falha ao buscar receitas.',
    deleteConfirmTitle: 'Você tem certeza absoluta?',
    deleteConfirmDescription:
      'Esta ação não pode ser desfeita. Isso excluirá permanentemente esta receita de nossos servidores.',
  },
  billPaymentsList: {
    noPayments: 'Nenhum pagamento de fatura registrado.',
    deleteSuccess: 'Pagamento de fatura excluído.',
    deleteError: 'Falha ao excluir pagamento de fatura.',
    fetchError: 'Falha ao buscar pagamentos de fatura.',
    deleteConfirmTitle: 'Excluir este pagamento?',
    deleteConfirmDescription:
      'Esta ação não pode ser desfeita. Isso excluirá permanentemente este registro de pagamento.',
  },
  lists: {
    expenses: 'Despesas',
    income: 'Receitas',
    billPayments: 'Pagamentos de Fatura',
  },
  common: {
    description: 'Descrição',
    amount: 'Valor',
    category: 'Categoria',
    mainCategory: 'Categoria Principal',
    subcategory: 'Subcategoria',
    date: 'Data',
    paymentMethod: 'Meio de Pagamento',
    actions: 'Ações',
    password: 'Senha',
    email: 'Email',
    cancel: 'Cancelar',
    delete: 'Excluir',
    rename: 'Renomear',
    error: 'Erro',
    success: 'Sucesso',
    options: 'Opções',
    previous: 'Anterior',
    next: 'Próximo',
  },
  payBillForm: {
    title: 'Pagamento de Fatura',
    description: 'Registre o pagamento da fatura do seu cartão de crédito.',
    cardLabel: 'Cartão de Crédito',
    selectCardPlaceholder: 'Selecione um cartão',
    amountLabel: 'Valor Pago',
    paymentDateLabel: 'Data do Pagamento',
    submitButton: 'Registrar Pagamento',
    addSuccess: 'Pagamento de fatura adicionado com sucesso.',
    addError: 'Falha ao adicionar pagamento. Por favor, tente novamente.',
    notLoggedIn: 'Você precisa estar logado para registrar um pagamento.',
    validation: {
      cardRequired: 'Por favor, selecione um cartão.',
      amountRequired: 'O valor é obrigatório.',
      amountPositive: 'O valor deve ser maior que zero.',
    },
    billClosed: '(fatura fechada)',
    billToPay: (value: string) => `(a pagar: ${value})`,
    billOverdue: '(fatura vencida)',
    billPaid: '(fatura paga)',
    creditStatus: (value: string) => `(crédito de ${value})`,
    closedBillToPay: (value: string) => `(fatura fechou valor para pagar ${value})`
  },
};
