
// prettier-ignore
const genesis = {
  "abbrev": "gn",
  "name": "Gênesis",
  "chapters": [
    [
      "No princípio, Deus criou os céus e a terra.",
      "Era a terra sem forma e vazia; trevas cobriam a face do abismo, e o Espírito de Deus se movia sobre a face das águas.",
      "Disse Deus: \"Haja luz\", e houve luz.",
      "Deus viu que a luz era boa, e fez separação entre a luz e as trevas.",
      "Deus chamou à luz dia, e às trevas chamou noite. Passaram-se a tarde e a manhã; esse foi o primeiro dia.",
      "Depois disse Deus: \"Haja entre as águas um firmamento que separe águas de águas\".",
      "E assim foi. Deus fez o firmamento e separou as águas que estavam embaixo do firmamento das que estavam por cima.",
      "Ao firmamento, Deus chamou céu. Passaram-se a tarde e a manhã; esse foi o segundo dia.",
      "E disse Deus: \"Ajuntem-se num só lugar as águas que estão debaixo do céu, e apareça a parte seca\". E assim foi.",
      "À parte seca Deus chamou terra, e chamou mares ao conjunto das águas. E Deus viu que ficou bom.",
      "Então disse Deus: \"Cubra-se a terra de vegetação: plantas que dêem sementes e árvores cujos frutos produzam sementes de acordo com as suas espécies\". E assim foi.",
      "A terra fez brotar a vegetação: plantas que dão sementes de acordo com as suas espécies, e árvores cujos frutos produzem sementes de acordo com as suas espécies. E Deus viu que ficou bom.",
      "Passaram-se a tarde e a manhã; esse foi o terceiro dia.",
      "Disse Deus: \"Haja luminares no firmamento do céu para separar o dia da noite. Sirvam eles de sinais para marcar estações, dias e anos,",
      "e sirvam de luminares no firmamento do céu para iluminar a terra\". E assim foi.",
      "Deus fez os dois grandes luminares: o maior para governar o dia e o menor para governar a noite; fez também as estrelas.",
      "Deus os colocou no firmamento do céu para iluminar a terra,",
      "governar o dia e a noite, e fazer separação entre a luz e as trevas. E Deus viu que ficou bom.",
      "Passaram-se a tarde e a manhã; esse foi o quarto dia.",
      "Disse também Deus: \"Encham-se as águas de seres vivos, e voem as aves sobre a terra, sob o firmamento do céu\".",
      "Assim Deus criou os grandes animais aquáticos e os demais seres vivos que povoam as águas, de acordo com as suas espécies; e todas as aves, de acordo com as suas espécies. E Deus viu que ficou bom.",
      "Então Deus os abençoou, dizendo: \"Sejam férteis e multipliquem-se! Encham as águas dos mares! E multipliquem-se as aves na terra\".",
      "Passaram-se a tarde e a manhã; esse foi o quinto dia.",
      "E disse Deus: \"Produza a terra seres vivos de acordo com as suas espécies: rebanhos domésticos, animais selvagens e os demais seres vivos da terra, cada um de acordo com a sua espécie\". E assim fue![CDATA[
const genesis = {
  abbrev: 'gn',
  name: 'Gênesis',
  chapters: [
    [
      'No princípio, criou Deus os céus e a terra.',
      'A terra, porém, estava sem forma e vazia; havia trevas sobre a face do abismo, e o Espírito de Deus pairava por sobre as águas.',
      'Disse Deus: Haja luz; e houve luz.',
      'E viu Deus que a luz era boa; e fez separação entre a luz e as trevas.',
      'Chamou Deus à luz Dia e às trevas, Noite. Houve tarde e manhã, o primeiro dia.',
      'E disse Deus: Haja firmamento no meio das águas e separação entre águas e águas.',
      'Fez, pois, Deus o firmamento e separação entre as águas debaixo do firmamento e as águas sobre o firmamento. E assim se fez.',
      'E chamou Deus ao firmamento Céus. Houve tarde e manhã, o segundo dia.',
      'Disse também Deus: Ajuntem-se as águas debaixo dos céus num só lugar, e apareça a porção seca. E assim se fez.',
      'À porção seca chamou Deus Terra e ao ajuntamento das águas, Mares. E viu Deus que isso era bom.',
      'E disse: Produza a terra relva, ervas que deem semente e árvores frutíferas que deem fruto segundo a sua espécie, cuja semente esteja nele, sobre a terra. E assim se fez.',
      'A terra, pois, produziu relva, ervas que davam semente segundo a sua espécie e árvores que davam fruto, cuja semente estava nele, conforme a sua espécie. E viu Deus que isso era bom.',
      'Houve tarde e manhã, o terceiro dia.',
      'Disse também Deus: Haja luzeiros no firmamento dos céus, para fazerem separação entre o dia e a noite; e sejam eles para sinais, para estações, para dias e anos.',
      'E sejam para luzeiros no firmamento dos céus, para alumiar a terra. E assim se fez.',
      'Fez Deus os dois grandes luzeiros: o maior para governar o dia, e o menor para governar a noite; e fez também as estrelas.',
      'E os colocou no firmamento dos céus para alumiarem a terra,',
      'para governarem o dia e a noite e fazerem separação entre a luz и as trevas. E viu Deus que isso era bom.',
      'Houve tarde e manhã, o quarto dia.',
      'Disse também Deus: Povoem-se as águas de enxames de seres viventes; e voem as aves sobre a terra, sob o firmamento dos céus.',
      'Criou, pois, Deus os grandes animais marinhos e todos os seres viventes que rastejam, os quais povoavam as águas, segundo as suas espécies; e todas as aves, segundo as suas espécies. E viu Deus que isso era bom.',
      'E Deus os abençoou, dizendo: Sede fecundos, multiplicai-vos e enchei as águas dos mares; e, na terra, se multipliquem as aves.',
      'Houve tarde e manhã, o quinto dia.',
      'Disse também Deus: Produza a terra seres viventes, conforme a sua espécie: animais domésticos, répteis e animais selváticos, segundo a sua espécie. E assim se fez.',
      'E fez Deus os animais selváticos, segundo a sua espécie, e os animais domésticos, conforme a sua espécie, e todos os répteis da terra, conforme a sua espécie. E viu Deus que isso era bom.',
      'Também disse Deus: Façamos o homem à nossa imagem, conforme a nossa semelhança; tenha ele domínio sobre os peixes do mar, sobre as aves dos céus, sobre os animais domésticos, sobre toda a terra e sobre todos os répteis que rastejam pela terra.',
      'Criou Deus, pois, o homem à sua imagem, à imagem de Deus o criou; homem e mulher os criou.',
      'E Deus os abençoou e lhes disse: Sede fecundos, multiplicai-vos, enchei a terra e sujeitai-a; dominai sobre os peixes do mar, sobre as aves dos céus e sobre todo animal que rasteja pela terra.',
      'E disse Deus ainda: Eis que vos tenho dado todas as ervas que dão semente e se acham na superfície de toda a terra e todas as árvores em que há fruto que dê semente; isso vos será para mantimento.',
      'E a todos os animais da terra, e a todas as aves dos céus, e a todos os répteis da terra, em que há fôlego de vida, toda erva verde lhes será para mantimento. E assim se fez.',
      'Viu Deus tudo quanto fizera, e eis que era muito bom. Houve tarde e manhã, o sexto dia.',
    ],
    [
      'Assim, pois, foram acabados os céus e a terra e todo o seu exército.',
      'E, havendo Deus terminado no dia sétimo a sua obra, que fizera, descansou nesse dia de toda a sua obra que tinha feito.',
      'E abençoou Deus o dia sétimo e o santificou; porque nele descansou de toda a obra que, como Criador, fizera.',
      'Esta é a gênese dos céus e da terra quando foram criados, quando o SENHOR Deus os criou.',
      'Não havia ainda nenhuma planta do campo na terra, pois ainda nenhuma erva do campo havia brotado; porque o SENHOR Deus não fizera chover sobre a terra, e também não havia homem para lavrar o solo.',
      'Mas uma neblina subia da terra e regava toda a superfície do solo.',
      'Então, formou o SENHOR Deus ao homem do pó da terra e lhe soprou nas narinas o fôlego de vida, e o homem passou a ser alma vivente.',
      'E plantou o SENHOR Deus um jardim no Éden, na direção do Oriente, e pôs nele o homem que havia formado.',
      'Do solo fez o SENHOR Deus brotar toda sorte de árvores agradáveis à vista e boas para alimento; e também a árvore da vida no meio do jardim e a árvore do conhecimento do bem e do mal.',
      'E saía um rio do Éden para regar o jardim e dali se dividia, repartindo-se em quatro braços.',
      'O primeiro chama-se Pisom; é o que rodeia a terra de Havilá, onde há ouro.',
      'O ouro dessa terra é bom; também se encontram lá o bdélio e a pedra de ônix.',
      'O segundo rio chama-se Giom; é o que circunda a terra de Cuxe.',
      'O nome do terceiro rio é Tigre; é o que corre pelo oriente da Assíria. E o quarto é o Eufrates.',
      'Tomou, pois, o SENHOR Deus ao homem e o colocou no jardim do Éden para o cultivar e o guardar.',
      'E o SENHOR Deus lhe deu esta ordem: De toda árvore do jardim comerás livremente,',
      'mas da árvore do conhecimento do bem e do mal não comerás; porque, no dia em que dela comeres, certamente morrerás.',
      'Disse mais o SENHOR Deus: Não é bom que o homem esteja só; far-lhe-ei uma auxiliadora que lhe seja idônea.',
      'Havendo, pois, o SENHOR Deus formado da terra todos os animais do campo e todas as aves dos céus, trouxe-os ao homem, para ver como este lhes chamaria; e o nome que o homem desse a todos os seres viventes, esse seria o nome deles.',
      'Deu nome o homem a todos os animais domésticos, às aves dos céus e a todos os animais selváticos; para o homem, todavia, не se achava uma auxiliadora que lhe fosse idônea.',
      'Então, o SENHOR Deus fez cair pesado sono sobre o homem, e este adormeceu; tomou uma de suas costelas e fechou o lugar com carne.',
      'E a costela que o SENHOR Deus tomara ao homem, transformou-a numa mulher e lha trouxe.',
      'E disse o homem: Esta, afinal, é osso dos meus ossos e carne da minha carne; chamar-se-á varoa, porquanto do varão foi tomada.',
      'Por isso, deixa o homem pai e mãe e se une à sua mulher, tornando-se os dois uma só carne.',
      'Ora, um e outro, o homem e sua mulher, estavam nus e não se envergonhavam.',
    ],
    [
        'Mas a serpente, mais sagaz que todos os animais selváticos que o SENHOR Deus tinha feito, disse à mulher: É assim que Deus disse: Não comereis de toda árvore do jardim?',
        'Respondeu-lhe a mulher: Do fruto das árvores do jardim podemos comer,',
        'mas do fruto da árvore que está no meio do jardim, disse Deus: Dele não comereis, nem tocareis nele, para que não morrais.',
        'Então, a serpente disse à mulher: É certo que не morrereis.',
        'Porque Deus sabe que no dia em que dele comerdes se vos abrirão os olhos e, como Deus, sereis conhecedores do bem e do mal.',
        'Vendo a mulher que a árvore era boa para se comer, agradável aos olhos e árvore desejável para dar entendimento, tomou-lhe do fruto e comeu e deu também ao marido, e ele comeu.',
        'Abriram-se, então, os olhos de ambos; e, percebendo que estavam nus, coseram folhas de figueira e fizeram cintas para si.',
        'Quando ouviram a voz do SENHOR Deus, que andava no jardim pela viração do dia, esconderam-se da presença do SENHOR Deus, o homem e sua mulher, por entre as árvores do jardim.',
        'E chamou o SENHOR Deus ao homem e lhe perguntou: Onde estás?',
        'Ele respondeu: Ouvi a tua voz no jardim, e, porque estava nu, tive medo, e me escondi.',
        'Perguntou-lhe Deus: Quem te fez saber que estavas nu? Comeste da árvore de que te ordenei que não comesses?',
        'Então, disse o homem: A mulher que me deste por esposa, ela me deu da árvore, e eu comi.',
        'Disse o SENHOR Deus à mulher: Que é isso que fizeste? Respondeu a mulher: A serpente me enganou, e eu comi.',
        'Então, o SENHOR Deus disse à serpente: Visto que isso fizeste, maldita és entre todos os animais domésticos e o és entre todos os animais selváticos; rastejarás sobre o teu ventre e comerás pó todos os dias da tua vida.',
        'Porei inimizade entre ti e a mulher, entre a tua descendência e o seu descendente. Este te ferirá a cabeça, e tu lhe ferirás o calcanhar.',
        'E à mulher disse: Multiplicarei sobremodo os sofrimentos da tua gravidez; em meio de dores darás à luz filhos; o teu desejo será para o teu marido, e ele te governará.',
        'E a Adão disse: Visto que atendeste a voz de tua mulher e comeste da árvore que eu te ordenara não comesses, maldita é a terra por tua causa; em fadigas obterás dela o sustento durante os dias de tua vida.',
        'Ela produzirá também cardos e abrolhos, e tu comerás a erva do campo.',
        'No suor do rosto comerás o teu pão, até que tornes à terra, pois dela foste formado; porque tu és pó e ao pó tornarás.',
        'E deu o homem o nome de Eva a sua mulher, por ser a mãe de todos os seres humanos.',
        'Fez o SENHOR Deus vestimenta de peles para Adão e sua mulher e os vestiu.',
        'Então, disse o SENHOR Deus: Eis que o homem se tornou como um de nós, conhecedor do bem e do mal; assim, que não estenda a mão, e tome também da árvore da vida, e coma, e viva eternamente.',
        'O SENHOR Deus, por isso, o lançou fora do jardim do Éden, a fim de lavrar a terra de que fora tomado.',
        'E, expulso o homem, colocou querubins ao oriente do jardim do Éden e o refulgir de uma espada que se revolvia, para guardar o caminho da árvore da vida.',
    ],
    [
        'Coabitou o homem com Eva, sua mulher. Esta concebeu e deu à luz a Caim; então, disse: Adquiri um varão com o auxílio do SENHOR.',
        'Depois, deu à luz a Abel, seu irmão. Abel foi pastor de ovelhas, e Caim, lavrador.',
        'Aconteceu que no fim de uns tempos trouxe Caim do fruto da terra uma oferta ao SENHOR.',
        'Abel, por sua vez, trouxe das primícias do seu rebanho e da gordura deste. Agradou-se o SENHOR de Abel e de sua oferta;',
        'ao passo que de Caim e de sua oferta não se agradou. Irou-se, pois, sobremaneira, Caim, e descaiu-lhe o semblante.',
        'Então, lhe disse o SENHOR: Por que andas irado, e por que descaiu o teu semblante?',
        'Se procederes bem, não é certo que serás aceito? Se, todavia, procederes mal, eis que o pecado jaz à porta; o seu desejo será Contra![CDATA[
const genesis = {
  abbrev: 'gn',
  name: 'Gênesis',
  chapters: [
    [
      'No princípio, Deus criou os céus e a terra.',
      'A terra era sem forma e vazia; e havia trevas sobre a face do abismo, e o Espírito de Deus se movia sobre a face das águas.',
      'E disse Deus: Haja luz. E houve luz.',
      'E viu Deus que a luz era boa; e fez Deus separação entre a luz e as trevas.',
      'E Deus chamou à luz Dia, e às trevas chamou Noite. E foi a tarde e a manhã, o dia primeiro.',
      'E disse Deus: Haja um firmamento no meio das águas, e haja separação entre águas e águas.',
      'E fez Deus o firmamento, e fez separação entre as águas que estavam debaixo do firmamento e as águas que estavam sobre o firmamento. E assim foi.',
      'E chamou Deus ao firmamento Céus. E foi a tarde e a manhã, o dia segundo.',
      'E disse Deus: Ajuntem-se as águas debaixo dos céus num lugar, e apareça a porção seca. E assim foi.',
      'E chamou Deus à porção seca Terra, e ao ajuntamento das águas chamou Mares. E viu Deus que isso era bom.',
      'E disse Deus: Produza a terra relva, ervas que deem semente e árvores frutíferas que deem fruto segundo a sua espécie, cuja semente esteja nele sobre a terra. E assim foi.',
      'E a terra produziu relva, ervas que davam semente segundo a sua espécie e árvores que davam fruto, cuja semente estava nele, conforme a sua espécie. E viu Deus que isso era bom.',
      'E foi a tarde e a manhã, o dia terceiro.',
      'E disse Deus: Haja luzeiros no firmamento dos céus, para haver separação entre o dia e a noite; e sejam eles para sinais e para tempos determinados e para dias e anos.',
      'E sejam para luzeiros no firmamento dos céus, para alumiar a terra. E assim foi.',
      'E fez Deus os dois grandes luzeiros: o luzeiro maior para governar o dia, e o luzeiro menor para governar a noite; e fez as estrelas.',
      'E Deus os pôs no firmamento dos céus para alumiar a terra,',
      'E para governar o dia e a noite, e para fazer separação entre a luz e as trevas. E viu Deus que isso era bom.',
      'E foi a tarde e a manhã, o dia quarto.',
      'E disse Deus: Produzam as águas abundantemente répteis de alma vivente; e voem as aves sobre a face do firmamento dos céus.',
      'E Deus criou as grandes baleias, e todo o réptil de alma vivente que as águas abundantemente produziram conforme as suas espécies; e toda a ave de asas conforme a sua espécie. E viu Deus que isso era bom.',
      'E Deus os abençoou, dizendo: Frutificai e multiplicai-vos, e enchei as águas nos mares; e as aves se multipliquem na terra.',
      'E foi a tarde e a manhã, o dia quinto.',
      'E disse Deus: Produza a terra alma vivente conforme a sua espécie; gado, e répteis, e bestas-feras da terra conforme a sua espécie. E assim foi.',
      'E fez Deus as bestas-feras da terra conforme a sua espécie, e o gado conforme a sua espécie, e todo o réptil da terra conforme a sua espécie. E viu Deus que isso era bom.',
      'E disse Deus: Façamos o homem à nossa imagem, conforme a nossa semelhança; e domine sobre os peixes do mar, e sobre as aves dos céus, e sobre o gado, e sobre toda a terra, e sobre todo o réptil que se move sobre a terra.',
      'E criou Deus o homem à sua imagem; à imagem de Deus o criou; homem e mulher os criou.',
      'E Deus os abençoou e Deus lhes disse: Frutificai, e multiplicai-vos, e enchei a terra, e sujeitai-a; e dominai sobre os peixes do mar, e sobre as aves dos céus, e sobre todo o animal que se move sobre a terra.',
      'E disse Deus: Eis que vos tenho dado toda a erva que dá semente e que está sobre a face de toda a terra e toda a árvore em que há fruto de árvore que dá semente; ser-vos-ão para mantimento.',
      'E a todo o animal da terra, e a toda a ave dos céus, e a todo o réptil da terra, em que há alma vivente, toda a erva verde será para mantimento. E assim foi.',
      'E viu Deus tudo quanto tinha feito, e eis que era muito bom. E foi a tarde e a manhã, o dia sexto.',
    ],
    [
        'Assim os céus, a terra e todo o seu exército foram acabados.',
        'E, havendo Deus acabado no dia sétimo a sua obra, que tinha feito, descansou no sétimo dia de toda a sua obra, que tinha feito.',
        'E abençoou Deus o dia sétimo e o santificou; porque nele descansou de toda a sua obra, que Deus criara e fizera.',
        'Estas são as origens dos céus e da terra, quando foram criados; no dia em que o Senhor Deus fez a terra e os céus.',
        'E toda a planta do campo que ainda não estava na terra, e toda a erva do campo que ainda não brotava; porque ainda o Senhor Deus não tinha feito chover sobre a terra, e não havia homem para lavrar a terra.',
        'Um vapor, porém, subia da terra e regava toda a face da terra.',
        'E formou o Senhor Deus o homem do pó da terra e soprou em seus narizes o fôlego da vida; e o homem foi feito alma vivente.',
        'E plantou o Senhor Deus um jardim no Éden, da banda do Oriente; e pôs ali o homem que tinha formado.',
        'E o Senhor Deus fez brotar da terra toda a árvore agradável à vista e boa para comida; e a árvore da vida no meio do jardim, e a árvore da ciência do bem и do mal.',
        'E saía um rio do Éden para regar o jardim; e dali se dividia e se tornava em quatro braços.',
        'O nome do primeiro é Pisom; este é o que rodeia toda a terra de Havilá, onde há ouro.',
        'E o ouro dessa terra é bom; ali há o bdélio e a pedra sardônica.',
        'E o nome do segundo rio é Giom; este é o que rodeia toda a terra de Cuxe.',
        'E o nome do terceiro rio é Tigre; este é o que vai para a banda do oriente da Assíria. E o quarto rio é o Eufrates.',
        'E tomou o Senhor Deus o homem e o pôs no jardim do Éden para o lavrar e o guardar.',
        'E ordenou o Senhor Deus ao homem, dizendo: De toda a árvore do jardim comerás livremente,',
        'mas da árvore da ciência do bem e do mal, dela não comerás; porque, no dia em que dela comeres, certamente morrerás.',
        'E disse o Senhor Deus: Não é bom que o homem esteja só; far-lhe-ei uma adjutora que esteja como diante dele.',
        'Havendo, pois, o Senhor Deus formado da terra todo o animal do campo e toda a ave dos céus, os trouxe a Adão, para este ver como lhes chamaria; e tudo o que Adão chamou a toda a alma vivente, isso foi o seu nome.',
        'E Adão pôs os nomes a todo o gado, e às aves dos céus, e a todo o animal do campo; mas para o homem não se achava adjutora que estivesse como diante dele.',
        'Então, o Senhor Deus fez cair um sono pesado sobre Adão, e este adormeceu; e tomou uma das suas costelas e cerrou a carne em seu lugar.',
        'E da costela que o Senhor Deus tomou do homem formou uma mulher; e trouxe-a a Adão.',
        'E disse Adão: Esta é agora osso dos meus ossos e carne da minha carne; esta será chamada varoa, porquanto do varão foi tomada.',
        'Portanto, deixará o varão o seu pai e a sua mãe e apegar-se-á à sua mulher, e serão ambos uma só carne.',
        'E ambos estavam nus, o homem e a sua mulher; e não se envergonhavam.',
    ],
    // ... Capítulos 3 a 50 seriam muito longos para incluir aqui, mas a estrutura está pronta.
  ],
};

export default genesis;
